#!/bin/bash

function main() {

if [ $DESKTOP_SESSION == "plasma" ]; then
  password=$( kdialog --password "Entrez votre mot de passe SUDO" )
elif  [ $DESKTOP_SESSION == "plasmawayland" ]; then
  password=$( kdialog --password "Entrez votre mot de passe SUDO" )
elif  [ $DESKTOP_SESSION == "gnome" ]; then
  password=$( zenity --password --text="Entrez votre mot de passe SUDO" )
elif [ -f /usr/bin/zenity ]; then
  password=$( zenity --password --text="Entrez votre mot de passe SUDO" )
fi

#password=$(echo $pwd)

chkroot=$(echo $password | sudo -S whoami)
if [ "$password" = "" ]; then
main
exit
elif [ "$chkroot" != "root" ]; then
  if [ $DESKTOP_SESSION == "plasma" ]; then
    kdialog --error "Mauvais mot de passe"
  elif  [ $DESKTOP_SESSION == "plasmawayland" ]; then
    kdialog --error "Mauvais mot de passe"
  elif  [ $DESKTOP_SESSION == "gnome" ]; then
    zenity --error --text="Mauvais mot de passe"
  elif [ -f /usr/bin/zenity ]; then
    zenity --error --text="Mauvais mot de passe"
  fi
exit
fi

chmod +x data/*.sh
chmod +x extra/*.sh
chmod +x SECUREBOOT/*.sh

logo="./source/logo.png"

install_zenity="echo $password | sudo -S apt install -y zenity"

if [ -f /usr/bin/zenity ]; then
  if [ -f /usr/bin/yad ]; then
    echo "rien à faire"
  else
    (echo $password | sudo -S apt -y install yad bash-completion curl) | zenity --progress --pulsate --title="Préparation de YAD" --text="Installation de YAD" --auto-close
  fi
else
  if [[ -f /usr/bin/konsole ]] ; then
    konsole -- -e $install_zenity
    menu
  elif [[ -f /usr/bin/gnome-terminal ]] ; then
    gnome-terminal -x $install_zenity
  fi
  if [ -f /usr/bin/yad ]; then
    echo "rien à faire"
  else
    (echo $password | sudo -S apt -y install yad bash-completion curl) | zenity --progress --pulsate --title="Préparation de YAD" --text="Installation de YAD" --auto-close
  fi
fi

(echo $password | sudo -S apt-add-repository -y contrib && \
echo $password | sudo -S apt-add-repository -y non-free && \
echo $password | sudo -S dpkg --add-architecture i386) | yad --center --window-icon="$logo" --progress --pulsate --title "Préparation de système" --progress-text="installation des dépôts additionnels" --width 500 --height 100 --no-buttons --auto-close

if [ $DESKTOP_SESSION == "gnome" ]; then
  if [ -f /usr/bin/flatpak ]; then
  echo "Rien à faire."
  else
  (echo $password | sudo -S apt -y install gnome-software-plugin-flatpak flatpak && \
  flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo) | yad --center --window-icon="$logo" --progress --pulsate --title "Préparation de système Gnome" --progress-text="Configuration de Flatpak pour Gnome" --width 500 --height 100 --no-buttons --auto-close
  fi
fi

cp ./source/logo.png /tmp/
echo $password | sudo -S bash -e ./source/menu-gui.sh
}

main
