#!/bin/bash

###### ADD SOURCE HERE ######
source ./source/scripts-tui.sh
######

clear
# Root checker
if [[ $EUID -ne 0 ]]; then
	echo -e "\n---------------------------------------\n"
    echo -e "Setup: must be run logged as root (su - / sudo -i)" 1>&2
    echo -e "\n---------------------------------------\n"
	exit 1
fi

chmod +x ./data/*.sh

function menu1() {
clear
echo "          ------------------ POSTINSTALL DEBIAN TUI ------------------

1- Configurer SECUREBOOT et installer les Signatures 
2- Installer les drivers Nvidia
3- Installer les drivers AMD
4- Programmes Utilitaires / Additionnels 

0- Quitter

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  secureboot
    ;;
2)  nvidia1
    ;;
3)  amd1
    ;;
4)  tools1
    ;;
f|F)  neofrog
      ;;
0)  clear && exit 1
    ;;
*)  menu1
    ;;
esac


}

function nvidia1() {
clear
echo "          -------------------------- NVIDIA --------------------------

1- Installer driver Nvidia Stable LTS (Recommandé)
2- Autres drivers Nvidia (Pour utilisateurs Expérimentés !!)
3- Supprimer driver Nvidia

0- Retour

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  nvidia-stable
    ;;
2)  nvidia2
    ;;
3)  nvidia-rollback
    ;;
0)  menu1
    ;;
*)  nvidia1
    ;;
esac

}

function nvidia2() {
clear
echo "          -------------------------- NVIDIA - Autres Drivers --------------------------

1- Installer driver depuis le depot Nvidia Cuda (Nvidia-Latest Stable) (Recommandé/Officiel Nvidia)

          ----------------------- NVIDIA - Version TEST/DEV -----------------------

2- Installer driver Nvidia de Testing en pin 10 (Pour Debian Stable)
3- Installer driver Nvidia Experimental (Nvidia-dev, Necessite Sid pin 10 !)

0- Retour

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  nvidia-cuda
    ;;
2)  nvidia-testing-on-stable
    ;;
3)  nvidia-experimental
    ;;
0)  menu1
    ;;
*)  nvidia2
    ;;
esac

}


function amd1() {
clear
echo "          ---------------------------- AMD ---------------------------

1- Installer Mesa Kisak Fresh
2- Installer AMD Vulkan
3- Installer ROCM opencl et ROCM HIP

0- Retour

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  mesa-kisak
    ;;
2)  amd-vulkan
    ;;
3)  rocm
    ;;
0)  menu1
    ;;
*)  amd1
    ;;
esac

}


function tools1() {
clear
echo "          ---------------------------- TOOLS --------------------------

--- Gestionnaires de paquets ---

1- Installer Deb-Get (Debian Stable uniquement)
2- Installer Pacstall (AUR pour Debian)

--- Applications Gaming ---

3- Installer Steam
4- Installer Lutris (Dépôt additionnel OBS officiel)
5- Installer Wine-Staging (Dépôt additionnel officiel)
D- Installer Discord (Dépot additionnel "Javinator9889")

--- Outils Supplémentaires ---

6- Mettre à jour les Firmware-Linux à la dernière version GIT

7- Ajouter les dépôts Backports pour Debian Stable
8- Installer les repository de Sid (pin 10) 

9- Utiliser l'outil d'ajout de PPA pour Debian (EXPERTS !!)

0- Retour

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  deb-get
    ;;
2)  pacstall
    ;;
3)  steam
    ;;
4)  lutris
    ;;
d|D)  discord
    ;;
5)  wine-staging
    ;;
6)  update-firmware
    ;;
7)  backports
    ;;
8)  install-sid
    ;;
9)  add-ppa-debian
    ;;
0)  menu1
    ;;
*)  tools1
    ;;
esac

}

menu1
