#!/bin/bash

###### ADD SOURCE HERE ######
source ./source/scripts.sh
######

clear
# Root checker
if [[ $EUID -ne 0 ]]; then
	echo -e "\n---------------------------------------\n"
    echo -e "Setup: must be run logged as root (su - / sudo -i)" 1>&2
    echo -e "\n---------------------------------------\n"
	exit 1
fi

chmod +x ./data/*.sh

function menu1() {
clear
echo "          ------------------ POSTINSTALL DEBIAN TUI ------------------

1 - Nvidia
2 - AMD
3 - Utilitaires

0- Quitter

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  nvidia1
    ;;
2)  amd1
    ;;
3)  tools1
    ;;
0)  clear && exit 1
    ;;
*)  menu1
    ;;
esac


}

function nvidia1() {
clear
echo "          -------------------------- NVIDIA --------------------------

1- Installer driver Nvidia Stable (Recommandé)
2- Autres drivers Nvidia (Pour utilisateurs Expérimentés !!)
3- Supprimer driver Nvidia
4- Configurer Secureboot pour Nvidia

0- Retour

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  nvidia-stable
    ;;
2)  nvidia2
    ;;
3)  nvidia-rollback
    ;;
4)  secureboot
    ;;
0)  menu1
    ;;
*)  nvidia1
    ;;
esac

}

function nvidia2() {
clear
echo "          -------------------------- NVIDIA --------------------------

1- Installer driver Nvidia Experimental
2- Installer driver depuis le depot Nvidia Cuda (Compatible Secureboot)
3- Installer driver Nvidia de Testing en pin 10 (Pour Debian Stable)

0- Retour

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  nvidia-experimental
    ;;
2)  nvidia-cuda
    ;;
3)  nvidia-testing-on-stable
    ;;
0)  menu1
    ;;
*)  nvidia2
    ;;
esac

}







function amd1() {
clear
echo "          ---------------------------- AMD ---------------------------

1- Installer Mesa Kisak Fresh
2- Installer AMD Vulkan

0- Retour

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  mesa-kisak
    ;;
2)  amd-vulkan
    ;;
0)  menu1
    ;;
*)  amd1
    ;;
esac

}


function tools1() {
clear
echo "          ---------------------------- TOOLS --------------------------

1- Installer deb-get (Debian Stable uniquement)
2- Installer wine-staging
3- Installer pacstall

7- Ajouter les dépôts Backports pour Debian Stable
8- Installer les repository de Sid (pin 10) pour Debian Testing
9- Utiliser l'outil d'ajout de PPA pour Debian

0- Retour

"

read -n1 -p "Choix ? " choix

case "$choix" in

1)  deb-get
    ;;
2)  wine-staging
    ;;
3)  pacstall
    ;;
7)  backports
    ;;
8)  install-sid
    ;;
9)  add-ppa-debian
    ;;
0)  menu1
    ;;
*)  tools1
    ;;
esac

}

menu1
