#!/bin/bash

## ON AJOUTE ICI LES SOURCES
## CHAQUE SOURCE CONTIENT UNE FONCTION QUI EST CALL DANS LE MAIN

source ./source/menu.sh

## ON DECLARE LE MAIN

function main() {
# Script need curl
if test -x "$(command -v yad 2>/dev/null)"; then
  apt install yad
fi
pwd=$(yad --title="Driver installer" --text="Installation des drivers" --text-align="center" \
--form \
--field="Password:":H '')
password=$(echo $pwd | awk 'BEGIN {FS="|" } { print $1 }')
chmod +x data/*.sh
chkroot=$(echo $password | sudo -S whoami)
if [ "$password" = "" ]; then
exit
elif [ "$chkroot" != "root" ]; then
zenity --error --title "Wrong password" --text="Mauvais mot de passe"
exit
fi

## ON CALL LA FONCTION CONTENU DANS ./source/menu.sh
menu
}

## EN FIN DE FICHIER ON CALL LE MAIN
main
